In [2]:
import numpy as np
a=[6,3,2,]
sum=np.sum(a)
print("sum of array element is ",sum)
min=np.min(a)
print("min of array is",min)
max=np.max(a)
print("max array is ",max)
mean=np.mean(a)
print("mean of array is",mean)
med=np.median(a)
print("median if array elemnet is ",med)
cor=np.corrcoef(a)
print("correaltion coefficiant of array element is",cor)
std=np.std(a)
print("standard deviation of array elemtn is",std)

      

sum of array element is  11
min of array is 2
max array is  6
mean of array is 3.6666666666666665
median if array elemnet is  3.0
correaltion coefficiant of array element is 1.0
standard deviation of array elemtn is 1.699673171197595


In [3]:
mat=[[4,8,9],[6,9,4],[6,2,9]]
sum=np.sum(mat)
print("sum of array element is ",sum)
min=np.min(mat)
print("min of array is",min)
max=np.max(mat)
print("max array is ",max)
mean=np.mean(mat)
print("mean of array is",mean)
med=np.median(mat)
print("median if array elemnet is ",med)
cor=np.corrcoef(mat)
print("correaltion coefficiant of array element is",cor)
std=np.std(mat)
print("standard deviation of array elemtn is",std)

      


sum of array element is  57
min of array is 2
max array is  9
mean of array is 6.333333333333333
median if array elemnet is  6.0
correaltion coefficiant of array element is [[ 1.         -0.07509393  0.1076244 ]
 [-0.07509393  1.         -0.99946643]
 [ 0.1076244  -0.99946643  1.        ]]
standard deviation of array elemtn is 2.449489742783178


In [7]:
mat=np.array([[1,4,5],[2,8,7],[8,3,7]])
print(mat)
sum=np.sum(mat,axis=1)
print("sum of array element row-wise is ",sum)
sum=np.sum(mat,axis=0)
print("sum of array element colum-wise is",sum)
min=np.min(mat,axis=1)
print("min of array row-wise is",min)
max=np.max(mat,axis=0)
print("max array colum-wise is ",max)


[[1 4 5]
 [2 8 7]
 [8 3 7]]
sum of array element row-wise is  [10 17 18]
sum of array element colum-wise is [11 15 19]
min of array row-wise is [1 2 3]
max array colum-wise is  [8 8 7]


In [1]:
#lambda
def sum(a,b):
    return a+b

sum(4,5)

9

In [12]:
def cube(x):
    return x*x*x
cube(4)

64

In [14]:
lambda_cube=lambda y: y*y*y
lambda_cube(5)
    

125

In [17]:
def greater (a,b):
    if a>b:
        return a
    else:
        return b
greater (4,5)

5

In [18]:
#map
def add4(x):
    return x+4
list1=[4,8,7,3]
list2=list(map(add4,list1))
list2


[8, 12, 11, 7]

In [19]:
list3=list(map(lambda x:x+4,list1))
list3

[8, 12, 11, 7]

In [20]:
set_of_strings=['abc','def','xyz']
string_map_22=list(map(lambda my_string:my_string +'_2022',set_of_strings))
string_map_22

['abc_2022', 'def_2022', 'xyz_2022']

In [22]:
#filter
def oddeven(x):
    if x%2==0:
        return True
    else:
        return False
list1=[4,5,6,0,4]
evenlist=list(filter(oddeven,list1))
evenlist

[4, 6, 0, 4]

In [23]:
#reduce
from functools import reduce
def sum(x,y):
    return x+y
list1=[5,9,3]
s=reduce(sum,list1)
s

17